language: cpp
env:
  - WITH_EXAMPLES=1
  - WITH_TESTS=1
compiler:
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
script:
  - make
  - cd build/deploy/tests && ./ngrestjsontest
  - cd build/deploy/tests && ./test_server_client
